import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  RefreshCw,
  Edit3,
  Calendar,
  ExternalLink,
  Twitter,
  Linkedin,
  Globe,
  Hash,
  Clock,
  Wand2,
  Eye,
  X,
  AlertCircle,
  CheckCircle,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { getAutoGeneratedPosts, triggerAutoGeneration } from '../../api/marketing';

// Channel icons mapping
const CHANNEL_ICONS = {
  twitter: Twitter,
  linkedin: Linkedin,
  facebook: Globe,
  instagram: Globe,
  blog: Globe
};

// Channel colors
const CHANNEL_COLORS = {
  twitter: 'bg-sky-500',
  linkedin: 'bg-blue-600',
  facebook: 'bg-blue-500',
  instagram: 'bg-gradient-to-r from-purple-500 to-pink-500',
  blog: 'bg-emerald-500'
};

// Status colors
const STATUS_COLORS = {
  draft: 'bg-amber-100 text-amber-700 border-amber-200',
  scheduled: 'bg-blue-100 text-blue-700 border-blue-200',
  published: 'bg-green-100 text-green-700 border-green-200',
  idea: 'bg-gray-100 text-gray-700 border-gray-200'
};

// Truncate text
const truncateText = (text, maxLength) => {
  if (!text) return '';
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength) + '...';
};

// Format date
const formatDate = (dateStr) => {
  if (!dateStr) return '';
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  } catch {
    return '';
  }
};

/**
 * GeneratedPostCard - Individual auto-generated post card
 */
const GeneratedPostCard = ({ post, onEdit, onPreview }) => {
  const ChannelIcon = CHANNEL_ICONS[post.channel] || Globe;
  const channelColor = CHANNEL_COLORS[post.channel] || 'bg-gray-600';
  const statusColor = STATUS_COLORS[post.status] || STATUS_COLORS.draft;
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="bg-white rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden flex flex-col"
    >
      {/* Header */}
      <div className="px-4 pt-4 pb-2 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-lg ${channelColor} flex items-center justify-center`}>
            <ChannelIcon className="w-4 h-4 text-white" />
          </div>
          <span className="text-sm font-medium text-gray-600 capitalize">{post.channel}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className={`px-2 py-1 text-xs font-medium rounded-full border ${statusColor}`}>
            {post.status}
          </span>
          <div className="flex items-center gap-1 text-xs text-purple-600 bg-purple-50 px-2 py-1 rounded-full">
            <Wand2 className="w-3 h-3" />
            <span>AI</span>
          </div>
        </div>
      </div>
      
      {/* Content */}
      <div className="px-4 py-2 flex-1">
        <h4 className="font-semibold text-gray-900 text-sm leading-snug mb-2">
          {truncateText(post.title?.replace('[AI Generated] ', ''), 60)}
        </h4>
        <p className="text-gray-600 text-xs leading-relaxed mb-2">
          {truncateText(post.content, 100)}
        </p>
        
        {/* Source info */}
        {post.source_info?.title && (
          <div className="flex items-start gap-2 p-2 bg-gray-50 rounded-lg">
            <Sparkles className="w-3.5 h-3.5 text-purple-500 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-gray-500">Generated from:</p>
              <p className="text-xs font-medium text-gray-700 truncate">
                {truncateText(post.source_info.title, 50)}
              </p>
            </div>
          </div>
        )}
      </div>
      
      {/* Footer */}
      <div className="px-4 py-3 border-t border-gray-100 bg-gray-50/50">
        {/* Timestamp */}
        <div className="flex items-center gap-1 text-xs text-gray-500 mb-3">
          <Clock className="w-3.5 h-3.5" />
          <span>Generated {formatDate(post.auto_generated_at || post.created_at)}</span>
        </div>
        
        {/* Actions */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => onEdit(post)}
            className="flex-1 flex items-center justify-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-medium rounded-lg transition-colors"
          >
            <Edit3 className="w-3.5 h-3.5" />
            Edit & Publish
          </button>
          <button
            onClick={() => onPreview(post)}
            className="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
            title="Preview"
          >
            <Eye className="w-4 h-4" />
          </button>
          {post.source_info?.url && (
            <a
              href={post.source_info.url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
              title="View original trend"
            >
              <ExternalLink className="w-4 h-4" />
            </a>
          )}
        </div>
      </div>
    </motion.div>
  );
};

/**
 * PreviewModal - Modal for viewing generated post details
 */
const PreviewModal = ({ post, onClose, onEdit }) => {
  if (!post) return null;
  
  const ChannelIcon = CHANNEL_ICONS[post.channel] || Globe;
  const channelColor = CHANNEL_COLORS[post.channel] || 'bg-gray-600';
  
  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          transition={{ type: "spring", duration: 0.3 }}
          className="relative w-full max-w-2xl max-h-[90vh] bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-blue-50">
            <div className="flex items-center gap-3">
              <div className={`w-10 h-10 rounded-xl ${channelColor} flex items-center justify-center`}>
                <ChannelIcon className="w-5 h-5 text-white" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-gray-600 capitalize">{post.channel}</span>
                  <span className="flex items-center gap-1 text-xs text-purple-600 bg-purple-100 px-2 py-0.5 rounded-full">
                    <Wand2 className="w-3 h-3" />
                    AI Generated
                  </span>
                </div>
                <p className="text-xs text-gray-500">
                  {formatDate(post.auto_generated_at || post.created_at)}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/80 rounded-xl transition-colors"
            >
              <X className="w-5 h-5 text-gray-500" />
            </button>
          </div>
          
          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            <h2 className="text-xl font-bold text-gray-900 mb-4 leading-tight">
              {post.title?.replace('[AI Generated] ', '')}
            </h2>
            
            {/* Generated content */}
            <div className="prose prose-sm max-w-none text-gray-700 mb-6 p-4 bg-gray-50 rounded-xl border border-gray-100">
              <p className="whitespace-pre-wrap">{post.content}</p>
            </div>
            
            {/* Source trending post info */}
            {post.source_info?.title && (
              <div className="p-4 bg-purple-50 rounded-xl border border-purple-100">
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="w-4 h-4 text-purple-600" />
                  <span className="text-sm font-medium text-purple-700">Source Trend</span>
                </div>
                <h4 className="font-medium text-gray-900 mb-1">{post.source_info.title}</h4>
                {post.source_info.content && (
                  <p className="text-sm text-gray-600 mb-2">
                    {truncateText(post.source_info.content, 200)}
                  </p>
                )}
                <div className="flex items-center gap-4 text-xs text-gray-500">
                  {post.source_info.platform && (
                    <span className="capitalize">Source: {post.source_info.platform}</span>
                  )}
                  {post.source_info.category && (
                    <span className="capitalize">Category: {post.source_info.category}</span>
                  )}
                </div>
              </div>
            )}
          </div>
          
          {/* Footer actions */}
          <div className="flex items-center gap-3 px-6 py-4 border-t border-gray-100 bg-gray-50">
            <button
              onClick={() => {
                onEdit(post);
                onClose();
              }}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-xl transition-colors"
            >
              <Edit3 className="w-4 h-4" />
              Edit & Publish
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2.5 bg-white hover:bg-gray-100 text-gray-700 font-medium rounded-xl border border-gray-200 transition-colors"
            >
              Close
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

/**
 * LoadingSkeleton - Skeleton loader for posts
 */
const LoadingSkeleton = () => (
  <div className="bg-white rounded-xl border border-gray-200 p-4 animate-pulse">
    <div className="flex items-center gap-2 mb-3">
      <div className="w-8 h-8 rounded-lg bg-gray-200" />
      <div className="w-20 h-4 rounded bg-gray-200" />
      <div className="ml-auto flex gap-2">
        <div className="w-14 h-5 rounded-full bg-gray-200" />
        <div className="w-10 h-5 rounded-full bg-gray-200" />
      </div>
    </div>
    <div className="space-y-2">
      <div className="h-4 rounded bg-gray-200 w-3/4" />
      <div className="h-3 rounded bg-gray-200 w-full" />
      <div className="h-3 rounded bg-gray-200 w-2/3" />
    </div>
    <div className="mt-3 p-2 rounded-lg bg-gray-100">
      <div className="h-3 rounded bg-gray-200 w-1/2" />
    </div>
    <div className="mt-4 pt-3 border-t border-gray-100">
      <div className="h-3 rounded bg-gray-200 w-1/3 mb-3" />
      <div className="h-8 rounded-lg bg-gray-200 w-full" />
    </div>
  </div>
);

/**
 * GeneratedFromTrendingSection - Section showing AI-generated posts from trending topics
 */
const GeneratedFromTrendingSection = () => {
  const navigate = useNavigate();
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState(null);
  const [previewPost, setPreviewPost] = useState(null);
  const [scrollPosition, setScrollPosition] = useState(0);
  
  const POSTS_PER_VIEW = 4;
  
  // Fetch auto-generated posts
  const fetchPosts = useCallback(async () => {
    try {
      setError(null);
      const data = await getAutoGeneratedPosts(20);
      setPosts(data.content || []);
    } catch (err) {
      console.error('Failed to fetch auto-generated posts:', err);
      setError('Failed to load auto-generated posts.');
    } finally {
      setLoading(false);
    }
  }, []);
  
  // Initial fetch
  useEffect(() => {
    fetchPosts();
  }, [fetchPosts]);
  
  // Handle refresh / trigger generation
  const handleRefresh = useCallback(async () => {
    setRefreshing(true);
    setError(null);
    try {
      await triggerAutoGeneration();
      // Wait a bit for generation to complete
      await new Promise(resolve => setTimeout(resolve, 3000));
      await fetchPosts();
    } catch (err) {
      console.error('Failed to trigger auto-generation:', err);
      setError('Failed to generate new posts. Please try again.');
    } finally {
      setRefreshing(false);
    }
  }, [fetchPosts]);
  
  // Handle edit - navigate to editor with content
  const handleEdit = useCallback((post) => {
    navigate('/app/marketing/editor', {
      state: {
        initialPrompt: post.content,
        context: {
          autoGenerated: true,
          contentId: post.id,
          sourcePost: post.source_info
        }
      }
    });
  }, [navigate]);
  
  // Scroll handlers
  const canScrollLeft = scrollPosition > 0;
  const canScrollRight = scrollPosition < Math.max(0, posts.length - POSTS_PER_VIEW);
  
  const scrollLeft = () => {
    setScrollPosition(Math.max(0, scrollPosition - POSTS_PER_VIEW));
  };
  
  const scrollRight = () => {
    setScrollPosition(Math.min(posts.length - POSTS_PER_VIEW, scrollPosition + POSTS_PER_VIEW));
  };
  
  // Get visible posts
  const visiblePosts = posts.slice(scrollPosition, scrollPosition + POSTS_PER_VIEW);
  
  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-blue-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center">
              <Wand2 className="w-5 h-5 text-white" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">Generated from Trending</h3>
              <p className="text-sm text-gray-500">AI-generated posts from trending topics</p>
            </div>
          </div>
          
          <button
            onClick={handleRefresh}
            disabled={refreshing || loading}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 bg-white hover:bg-gray-50 border border-gray-200 rounded-lg transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
            {refreshing ? 'Generating...' : 'Generate New'}
          </button>
        </div>
      </div>
      
      {/* Content */}
      <div className="p-6">
        {error && (
          <div className="flex items-center gap-3 p-4 mb-4 bg-red-50 border border-red-200 rounded-xl text-red-700">
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            <span className="text-sm">{error}</span>
            <button
              onClick={handleRefresh}
              className="ml-auto text-sm font-medium underline hover:no-underline"
            >
              Try again
            </button>
          </div>
        )}
        
        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[...Array(4)].map((_, i) => (
              <LoadingSkeleton key={i} />
            ))}
          </div>
        ) : posts.length === 0 ? (
          <div className="text-center py-12">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-purple-100 flex items-center justify-center">
              <Wand2 className="w-8 h-8 text-purple-500" />
            </div>
            <h4 className="text-lg font-medium text-gray-900 mb-2">No generated posts yet</h4>
            <p className="text-gray-500 mb-4 max-w-md mx-auto">
              Click "Generate New" to create AI-powered posts from the latest trending topics.
            </p>
            <button
              onClick={handleRefresh}
              disabled={refreshing}
              className="inline-flex items-center gap-2 px-4 py-2 bg-purple-600 text-white text-sm font-medium rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50"
            >
              <Sparkles className="w-4 h-4" />
              {refreshing ? 'Generating...' : 'Generate Posts'}
            </button>
          </div>
        ) : (
          <div className="relative">
            {/* Navigation arrows */}
            {canScrollLeft && (
              <button
                onClick={scrollLeft}
                className="absolute -left-3 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-full bg-white shadow-lg border border-gray-200 flex items-center justify-center hover:bg-gray-50 transition-colors"
              >
                <ChevronLeft className="w-5 h-5 text-gray-600" />
              </button>
            )}
            {canScrollRight && (
              <button
                onClick={scrollRight}
                className="absolute -right-3 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-full bg-white shadow-lg border border-gray-200 flex items-center justify-center hover:bg-gray-50 transition-colors"
              >
                <ChevronRight className="w-5 h-5 text-gray-600" />
              </button>
            )}
            
            {/* Posts grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <AnimatePresence mode="popLayout">
                {visiblePosts.map((post) => (
                  <GeneratedPostCard
                    key={post.id}
                    post={post}
                    onEdit={handleEdit}
                    onPreview={setPreviewPost}
                  />
                ))}
              </AnimatePresence>
            </div>
            
            {/* Pagination dots */}
            {posts.length > POSTS_PER_VIEW && (
              <div className="flex items-center justify-center gap-1.5 mt-4">
                {Array.from({ length: Math.ceil(posts.length / POSTS_PER_VIEW) }).map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => setScrollPosition(idx * POSTS_PER_VIEW)}
                    className={`w-2 h-2 rounded-full transition-colors ${
                      Math.floor(scrollPosition / POSTS_PER_VIEW) === idx
                        ? 'bg-purple-600'
                        : 'bg-gray-300 hover:bg-gray-400'
                    }`}
                  />
                ))}
              </div>
            )}
          </div>
        )}
      </div>
      
      {/* Preview Modal */}
      {previewPost && (
        <PreviewModal
          post={previewPost}
          onClose={() => setPreviewPost(null)}
          onEdit={handleEdit}
        />
      )}
    </div>
  );
};

export default GeneratedFromTrendingSection;
