import apiClient from './index';

/**
 * Marketing dashboard aggregate: scheduled_next_7_days, draft_count, campaigns_with_dates, pending_approvals.
 */
export async function getMarketingDashboard() {
  const response = await apiClient.get('/marketing/dashboard');
  return response.data;
}

/**
 * List content calendar items.
 * @param {{ campaign_id?: string, status?: string, channel?: string, start_date?: string, end_date?: string, limit?: number, offset?: number }} params
 */
export async function listContent(params = {}) {
  const response = await apiClient.get('/marketing/content', { params });
  return response.data;
}

/**
 * Update a content calendar item.
 * @param {string} contentId - Content ID to update
 * @param {{ title?: string, content?: string, channel?: string, status?: string, media_files?: Array }} data - Update data
 * @returns {Promise<object>}
 */
export async function updateContent(contentId, data) {
  const response = await apiClient.put(`/marketing/content/${contentId}`, data);
  return response.data;
}

/**
 * List campaigns.
 * @param {{ status?: string, limit?: number, offset?: number }} params
 */
export async function listCampaigns(params = {}) {
  const response = await apiClient.get('/marketing/campaigns', { params });
  return response.data;
}

// =============================================================================
// Social Media Trends API
// =============================================================================

/**
 * Get trending social media posts.
 * @param {string} category - Category filter: tech, marketing, business, finance, health, lifestyle, entertainment, or 'all'
 * @param {number} limit - Maximum number of posts to return (default: 20)
 * @returns {Promise<{items: Array, category: string, total: number}>}
 */
export async function getTrendingPosts(category = 'all', limit = 20) {
  const response = await apiClient.get('/marketing/trends', { 
    params: { category, limit } 
  });
  return response.data;
}

/**
 * Get list of available trend categories.
 * @returns {Promise<{categories: Array<{id: string, label: string}>}>}
 */
export async function getTrendCategories() {
  const response = await apiClient.get('/marketing/trends/categories');
  return response.data;
}

/**
 * Force refresh trends for a category.
 * @param {string} category - Category to refresh (default: 'all')
 * @returns {Promise<{success: boolean, category: string, count: number, message: string}>}
 */
export async function refreshTrends(category = 'all') {
  const response = await apiClient.post('/marketing/trends/refresh', { category });
  return response.data;
}

// =============================================================================
// Auto-Generated Content API
// =============================================================================

/**
 * Get auto-generated posts from trending topics.
 * @param {number} limit - Maximum number of posts to return (default: 20)
 * @returns {Promise<{content: Array, count: number}>}
 */
export async function getAutoGeneratedPosts(limit = 20) {
  const response = await apiClient.get('/marketing/content/autogenerated', {
    params: { limit }
  });
  return response.data;
}

/**
 * Trigger auto-generation of content from trending posts.
 * @returns {Promise<{success: boolean, message: string}>}
 */
export async function triggerAutoGeneration() {
  const response = await apiClient.post('/marketing/content/autogenerated/trigger');
  return response.data;
}

// =============================================================================
// Social Connections API
// =============================================================================

/**
 * Get list of social media connections for the current user.
 * @returns {Promise<{connections: Array, available_platforms: Array}>}
 */
export async function getSocialConnections() {
  const response = await apiClient.get('/marketing/social/connections');
  return response.data;
}

/**
 * Initiate OAuth connection for a social platform.
 * @param {string} platform - Platform to connect: twitter, linkedin, facebook, instagram
 * @returns {Promise<{auth_url: string, status: string, message: string, connection_id: string}>}
 */
export async function connectSocialPlatform(platform) {
  const response = await apiClient.post(`/marketing/social/connect/${platform}`);
  return response.data;
}

/**
 * Check connection status for a platform.
 * @param {string} platform - Platform to check
 * @returns {Promise<{platform: string, connected: boolean, status: string, profile_name?: string}>}
 */
export async function checkConnectionStatus(platform) {
  const response = await apiClient.get(`/marketing/social/connections/${platform}/status`);
  return response.data;
}

/**
 * Disconnect a social media platform.
 * @param {string} platform - Platform to disconnect
 * @returns {Promise<{deleted: boolean, platform: string}>}
 */
export async function disconnectSocialPlatform(platform) {
  const response = await apiClient.delete(`/marketing/social/connections/${platform}`);
  return response.data;
}

// =============================================================================
// Publishing API
// =============================================================================

/**
 * Publish content to social media platforms.
 * @param {string} contentId - Content calendar ID to publish
 * @param {Array<string>} platforms - Platforms to publish to
 * @param {object} platformOptions - Platform-specific options (e.g., {facebook: {page_id: "123"}})
 * @returns {Promise<{content_id: string, results: object, all_successful: boolean}>}
 */
export async function publishContent(contentId, platforms, platformOptions = {}) {
  const response = await apiClient.post(`/marketing/publish/${contentId}`, {
    platforms,
    platform_options: platformOptions
  });
  return response.data;
}

/**
 * Validate content against platform constraints.
 * @param {string} content - Content text to validate
 * @param {string} platform - Platform to validate for
 * @param {number} mediaCount - Number of media files
 * @returns {Promise<{valid: boolean, platform: string, errors: Array, warnings: Array, character_count: number, character_limit: number}>}
 */
export async function validateContent(content, platform, mediaCount = 0) {
  const response = await apiClient.post('/marketing/publish/validate', {
    content,
    platform,
    media_count: mediaCount
  });
  return response.data;
}

/**
 * Get platform constraints and limits.
 * @returns {Promise<{platforms: object}>}
 */
export async function getPlatformInfo() {
  const response = await apiClient.get('/marketing/publish/platforms');
  return response.data;
}

// =============================================================================
// Marketing Images API
// =============================================================================

/**
 * Generate an AI image for marketing content.
 * @param {string} prompt - Image generation prompt
 * @param {object} options - Generation options
 * @param {string} options.content_id - Optional content ID to link to
 * @param {string} options.aspect_ratio - Aspect ratio: 1:1, 16:9, 4:5, 9:16, 2:1
 * @param {string} options.style - Style: professional, creative, minimalist, bold
 * @param {string} options.category - Category: social, blog, email, general
 * @returns {Promise<{success: boolean, id: string, file_url: string, ...}>}
 */
export async function generateMarketingImage(prompt, options = {}) {
  const response = await apiClient.post('/marketing/images/generate', {
    prompt,
    content_id: options.content_id,
    aspect_ratio: options.aspect_ratio || '1:1',
    style: options.style || 'professional',
    category: options.category || 'social'
  });
  return response.data;
}

/**
 * List marketing images.
 * @param {object} params - Filter parameters
 * @param {string} params.category - Filter by category
 * @param {string} params.source - Filter by source: ai_generated, uploaded, gallery
 * @param {string} params.content_id - Filter by linked content
 * @param {number} params.limit - Max results (default 50)
 * @param {number} params.offset - Pagination offset
 * @returns {Promise<{images: Array, limit: number, offset: number}>}
 */
export async function getMarketingImages(params = {}) {
  const response = await apiClient.get('/marketing/images', { params });
  return response.data;
}

/**
 * Get a single marketing image by ID.
 * @param {string} imageId - Image ID
 * @returns {Promise<object>}
 */
export async function getMarketingImage(imageId) {
  const response = await apiClient.get(`/marketing/images/${imageId}`);
  return response.data;
}

/**
 * Upload an image for marketing use.
 * @param {File} file - Image file to upload
 * @param {string} category - Image category
 * @param {string} contentId - Optional content ID to link to
 * @returns {Promise<{success: boolean, id: string, file_url: string, ...}>}
 */
export async function uploadMarketingImage(file, category = 'general', contentId = null) {
  const formData = new FormData();
  formData.append('file', file);
  
  const params = new URLSearchParams({ category });
  if (contentId) params.append('content_id', contentId);
  
  const response = await apiClient.post(`/marketing/images/upload?${params}`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
  return response.data;
}

/**
 * Attach an image to content.
 * @param {string} contentId - Content calendar ID
 * @param {string} imageId - Image ID to attach
 * @returns {Promise<{attached: boolean, image_id: string, content_id: string}>}
 */
export async function attachImageToContent(contentId, imageId) {
  const response = await apiClient.post(`/marketing/images/content/${contentId}/attach`, {
    image_id: imageId
  });
  return response.data;
}

/**
 * Detach an image from content.
 * @param {string} contentId - Content calendar ID
 * @param {string} imageId - Image ID to detach
 * @returns {Promise<{detached: boolean}>}
 */
export async function detachImageFromContent(contentId, imageId) {
  const response = await apiClient.delete(`/marketing/images/content/${contentId}/detach/${imageId}`);
  return response.data;
}

/**
 * Delete a marketing image.
 * @param {string} imageId - Image ID to delete
 * @returns {Promise<{deleted: boolean}>}
 */
export async function deleteMarketingImage(imageId) {
  const response = await apiClient.delete(`/marketing/images/${imageId}`);
  return response.data;
}

/**
 * Get available aspect ratios for image generation.
 * @returns {Promise<{aspect_ratios: object}>}
 */
export async function getAspectRatios() {
  const response = await apiClient.get('/marketing/images/aspect-ratios');
  return response.data;
}
