import apiClient from './index';

/**
 * Marketing dashboard aggregate: scheduled_next_7_days, draft_count, campaigns_with_dates, pending_approvals.
 */
export async function getMarketingDashboard() {
  const response = await apiClient.get('/marketing/dashboard');
  return response.data;
}

/**
 * List content calendar items.
 * @param {{ campaign_id?: string, status?: string, channel?: string, start_date?: string, end_date?: string, limit?: number, offset?: number }} params
 */
export async function listContent(params = {}) {
  const response = await apiClient.get('/marketing/content', { params });
  return response.data;
}

/**
 * List campaigns.
 * @param {{ status?: string, limit?: number, offset?: number }} params
 */
export async function listCampaigns(params = {}) {
  const response = await apiClient.get('/marketing/campaigns', { params });
  return response.data;
}

// =============================================================================
// Social Media Trends API
// =============================================================================

/**
 * Get trending social media posts.
 * @param {string} category - Category filter: tech, marketing, business, finance, health, lifestyle, entertainment, or 'all'
 * @param {number} limit - Maximum number of posts to return (default: 20)
 * @returns {Promise<{items: Array, category: string, total: number}>}
 */
export async function getTrendingPosts(category = 'all', limit = 20) {
  const response = await apiClient.get('/marketing/trends', { 
    params: { category, limit } 
  });
  return response.data;
}

/**
 * Get list of available trend categories.
 * @returns {Promise<{categories: Array<{id: string, label: string}>}>}
 */
export async function getTrendCategories() {
  const response = await apiClient.get('/marketing/trends/categories');
  return response.data;
}

/**
 * Force refresh trends for a category.
 * @param {string} category - Category to refresh (default: 'all')
 * @returns {Promise<{success: boolean, category: string, count: number, message: string}>}
 */
export async function refreshTrends(category = 'all') {
  const response = await apiClient.post('/marketing/trends/refresh', { category });
  return response.data;
}

// =============================================================================
// Auto-Generated Content API
// =============================================================================

/**
 * Get auto-generated posts from trending topics.
 * @param {number} limit - Maximum number of posts to return (default: 20)
 * @returns {Promise<{content: Array, count: number}>}
 */
export async function getAutoGeneratedPosts(limit = 20) {
  const response = await apiClient.get('/marketing/content/autogenerated', {
    params: { limit }
  });
  return response.data;
}

/**
 * Trigger auto-generation of content from trending posts.
 * @returns {Promise<{success: boolean, message: string}>}
 */
export async function triggerAutoGeneration() {
  const response = await apiClient.post('/marketing/content/autogenerated/trigger');
  return response.data;
}
